// Importation des types et des composants nécessaires
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

// Configuration de la police Inter avec le sous-ensemble latin
const inter = Inter({ subsets: ["latin"] });

// Définition des métadonnées pour le document HTML
export const metadata: Metadata = {
  title: "Create Next App", // Titre de la page
  description: "Generated by create next app", // Description de la page
};

// Définition du composant RootLayout
// Il prend en paramètre un objet contenant une propriété "children" de type ReactNode
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Le composant retourne un fournisseur ClerkProvider qui englobe un document HTML
  // Le document HTML contient un corps avec la police Inter et un fournisseur de thème
  return (
    <ClerkProvider>
      <html lang="fr" suppressHydrationWarning>
        <body className={cn("bg-secondary", inter.className)}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
